Gdpm 45 liste erstellter modelle anzeigen
Projektstudium-HTW-WiSe2022-23/gdpm pull request #14
Opened 2023-03-22 19:08 UTC by VulcanTest

2023-03-23 02:50 UTC, lucasgarbe approved these changes

2023-03-23 13:14 UTC, bf-malefiz requested changes
Der branch ist nicht auf dem aktuellsten Stand des develop branch. Nach merge von develop kommt folgender Fehler beim builden:

#0 2.324 3:16  Error: Component definition is missing display name  react/display-name
#0 2.324
#0 2.324 ./components/distributionNode.tsx
#0 2.324 14:28  Error: React Hook "useStore" is called in function "distributionNode: FC<Node<NodeData>>" that is neitheer a React function component nor a custom React Hook function. React component names must start with an uppercase letterr. React Hook names must start with the word "use".  react-hooks/rules-of-hooks

Bitte vor dem PR den branch aktualisieren und den Fehler beheben

2023-03-23 23:28 UTC, lucasgarbe approved these changes

2023-03-24 01:06 UTC, bf-malefiz approved these changes

2023-03-24 01:06 UTC, merged